services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nisayang
    ports:
      - "8100:80"
    volumes:
      - ./app/www/html/:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

